# Generated by Django 3.0.4 on 2020-06-16 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_delivery', '0002_auto_20200616_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='pratos',
        ),
        migrations.AddField(
            model_name='pedido',
            name='pratos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_delivery.Cesta'),
        ),
    ]
